name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs
      - uses: gradle/gradle-build-action@v2
        name: Build and upload container
        with:
          arguments: jib -Djib.to.auth.username=$USERNAME -Djib.to.auth.password=$PASSWORD
